export enum InterviewSessionStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_VALIDATION = 'AWAITING_VALIDATION',
  COMPLETED = 'COMPLETED',
  EXPIRED = 'EXPIRED',
  ABANDONED = 'ABANDONED',
}

export enum MessageRole {
  SYSTEM = 'SYSTEM',
  ASSISTANT = 'ASSISTANT',
  USER = 'USER',
}

export enum SignalCategory {
  BUYER_IDENTITY = 'BUYER_IDENTITY',
  BUYER_MOTIVATION = 'BUYER_MOTIVATION',
  PROPERTY_PREFERENCE = 'PROPERTY_PREFERENCE',
  FINANCIAL_READINESS = 'FINANCIAL_READINESS',
  BEHAVIORAL = 'BEHAVIORAL',
  TIMELINE = 'TIMELINE',
  ENGAGEMENT = 'ENGAGEMENT',
}

export enum BuyerClassification {
  RESEARCH_STAGE = 'RESEARCH_STAGE',
  EARLY_BUYER = 'EARLY_BUYER',
  ACTIVE_BUYER = 'ACTIVE_BUYER',
  HIGH_PROBABILITY = 'HIGH_PROBABILITY',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  GENERATING = 'GENERATING',
  READY = 'READY',
  EXPORTED = 'EXPORTED',
  ERROR = 'ERROR',
}

export enum WorkflowStatus {
  NEW = 'NEW',
  INTERVIEW_SENT = 'INTERVIEW_SENT',
  INTERVIEW_COMPLETE = 'INTERVIEW_COMPLETE',
  REPORT_READY = 'REPORT_READY',
  ACTION_TAKEN = 'ACTION_TAKEN',
  FOLLOW_UP = 'FOLLOW_UP',
  CLOSED = 'CLOSED',
}

export enum RecommendedAction {
  SEND_TO_LENDER = 'SEND_TO_LENDER',
  SCHEDULE_CONSULTATION = 'SCHEDULE_CONSULTATION',
  ADD_TO_FOLLOW_UP = 'ADD_TO_FOLLOW_UP',
}
